### ISSUE TITLE
Scope of the accounts-ui-* packages

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/accounts-ui-semantic#1]
Great to see a start on this. I was thinking we could even keep the Blaze Component in the accounts-ui package, so that these markup specific packages would just contain the templates. Thoughts?

**Comment by DominikGuzei** [comment]
Ah ok, yeah good thought! Will refactor that back ;-)

**Comment by DominikGuzei** [comment]
Althought … we could also keep it like now, and even remove the dependency on Blaze that way! What about devs that use React?

**Comment by rhyslbw** [comment]
That's a good point :-) So this is really space:accounts-ui-blaze-semantic!

**Comment by rhyslbw** [comment]
It's getting crazy in here but this is the nature of the beast! Client-side and UI in meteor now has many levels. Imagine space:accounts-ui-blaze that just adds the components, then this package and others such as Bootstrap provide just the templates. The end user still just has to add the end package they want to use "I'm using Blaze and Semantic UI"…

**Comment by DominikGuzei** [comment]
Yep, in the long run it could end like this :wink: for now i would just develop this package – it's easy to refactor the components out later!

**Comment by rhyslbw** [comment]
Ok so the first time we consider a new package of this nature would be the best time to refactor.

**Comment by DominikGuzei** [comment]
Yeah, if someone comes and says "hey i wanna build the same thing with bootstrap" then we can do this. Now it would just be more work without any direct benefits :wink:
